// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe4DH0Nq4B5-h-DUxFHpfkraoRBz0Y3q8',
    appId: '1:461676819976:web:3fa92910ceba9455ff43bd',
    messagingSenderId: '461676819976',
    projectId: 'fittrack-fb490',
    authDomain: 'fittrack-fb490.firebaseapp.com',
    storageBucket: 'fittrack-fb490.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs8Nwl3465TSL5aBokck32nCxr9dQN0bE',
    appId: '1:461676819976:android:5fd117c9cd0e3393ff43bd',
    messagingSenderId: '461676819976',
    projectId: 'fittrack-fb490',
    storageBucket: 'fittrack-fb490.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABCl1sMkmdOpc5DGrLuc-hki-nTBjzmGs',
    appId: '1:461676819976:ios:8320474efec3f2f5ff43bd',
    messagingSenderId: '461676819976',
    projectId: 'fittrack-fb490',
    storageBucket: 'fittrack-fb490.firebasestorage.app',
    iosBundleId: 'com.example.fitTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABCl1sMkmdOpc5DGrLuc-hki-nTBjzmGs',
    appId: '1:461676819976:ios:8320474efec3f2f5ff43bd',
    messagingSenderId: '461676819976',
    projectId: 'fittrack-fb490',
    storageBucket: 'fittrack-fb490.firebasestorage.app',
    iosBundleId: 'com.example.fitTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe4DH0Nq4B5-h-DUxFHpfkraoRBz0Y3q8',
    appId: '1:461676819976:web:cd98f670a70ca326ff43bd',
    messagingSenderId: '461676819976',
    projectId: 'fittrack-fb490',
    authDomain: 'fittrack-fb490.firebaseapp.com',
    storageBucket: 'fittrack-fb490.firebasestorage.app',
  );
}
